### PR TITLE
Add tgz output to results

### PR DESCRIPTION
**Pull request by crosbymichael**
I really don't have a good way to test this but I think it will work...

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by kencochrane** [comment]
LGTM

**Comment by jessfraz** [comment]
LGTM

**Comment by jessfraz** [comment]
i cant merge lolz

**Comment by crosbymichael** [comment]
wtf

**Comment by crosbymichael** [comment]
it works https://master.dockerproject.org/

**Pull request merged**
